/* keywords only in lower case */

/* http://unicode.org/emoji/charts/full-emoji-list.html */
	
var ALL_KEYWORDS = [
	[		// --- smileys
		['grinning face'],
		['grinning face with big eyes'],
		['grinning face with smiling eyes'],
		['beaming face with smiling eyes'],
		['grinning squinting face'],
		['grinning face with sweat'],
		['rolling on the floor laughing'],
		['face with tears of joy'],
		['slightly smiling face'],
		['upside-down face'],
		['winking face'],
		['smiling face with smiling eyes'],
		['smiling face with halo'],
		['smiling face with heart-eyes'],
		['star-struck'],
		['face blowing kiss'],
		['kissing face'],
		['smiling face'],
		['kissing face with closed eyes'],
		['kissing face with smiling eyes'],
		['face savoring food'],
		['face with tongue'],
		['winking face with tongue'],
		['zany face'],
		['squinting face with tongue'],
		['money-mouth face'],
		['hugging face'],
		['face with hand over mouth'],
		['shushing face'],
		['thinking face'],
		['zipper-mouth face'],
		['face with raised eyebrow'],
		['neutral face'],
		['expressionless face'],
		['face without mouth'],
		['smirking face'],
		['unamused face'],
		['face with rolling eyes'],
		['grimacing face'],
		['lying face'],
		['relieved face'],
		['pensive face'],
		['sleepy face'],
		['drooling face'],
		['sleeping face'],
		['face with medical mask'],
		['face with thermometer'],
		['face with head-bandage'],
		['nauseated face'],
		['face vomiting'],
		['sneezing face'],
		['hot face'],
		['cold face'],
		['woozy face'],
		['dizzy face'],
		['exploding head'],
		['cowboy hat face'],
		['partying face'],
		['smiling face with sunglasses'],
		['nerd face'],
		['face with monocle'],
		['confused face'],
		['worried face'],
		['slightly frowning face'],
		['frowning face'],
		['face with open mouth'],
		['hushed face'],
		['astonished face'],
		['flushed face'],
		['pleading face'],
		['frowning face with open mouth'],
		['anguished face'],
		['fearful face'],
		['anxious face with sweat'],
		['sad but relieved face'],
		['crying face'],
		['loudly crying face'],
		['face screaming in fear'],
		['confounded face'],
		['persevering face'],
		['disappointed face'],
		['downcast face with sweat'],
		['weary face'],
		['tired face'],
		['face with steam from nose'],
		['pouting face'],
		['angry face'],
		['face with symbols on mouth'],
		['smiling face with horns'],
		['angry face with horns'],
		['skull'],
		['skull and crossbones'],
		['pile of poo'],
		['clown face'],
		['ogre'],
		['goblin'],
		['ghost'],
		['alien'],
		['alien monster'],
		['robot face'],
		['grinning cat face'],
		['grinning cat face with smiling eyes'],
		['cat face with tears of joy'],
		['smiling cat face with heart-eyes'],
		['cat face with wry smile'],
		['kissing cat face'],
		['weary cat face'],
		['crying cat face'],
		['pouting cat face'],
		['see-no-evil monkey'],
		['hear-no-evil monkey'],
		['speak-no-evil monkey']
	], [	// --- body
		['waving hand'],
		['raised back of hand'],
		['hand with fingers splayed'],
		['raised hand'],
		['vulcan salute'],
		['OK hand'],
		['victory hand'],
		['crossed fingers'],
		['love-you gesture'],
		['sign of the horns'],
		['call me hand'],
		['backhand index pointing left'],
		['backhand index pointing right'],
		['backhand index pointing up'],
		['middle finger'],
		['backhand index pointing down'],
		['index pointing up'],
		['thumbs up'],
		['thumbs down'],
		['raised fist'],
		['oncoming fist'],
		['left-facing fist'],
		['right-facing fist'],
		['clapping hands'],
		['raising hands'],
		['open hands'],
		['palms up together'],
		['handshake'],
		['folded hands'],
		['writing hand'],
		['nail polish'],
		['selfie'],
		['flexed biceps'],
		['leg'],
		['foot'],
		['ear'],
		['nose'],
		['brain'],
		['tooth'],
		['bone'],
		['eyes'],
		['eye'],
		['tongue'],
		['mouth'],
		['red hair'],
		['curly hair'],
		['white hair'],
		['bald'],
		['speaking head'],
		['bust in silhouette'],
		['busts in silhouette'],
		['footprints']
	], [	// --- people
		['baby'],
		['child'],
		['boy'],
		['girl'],
		['person'],
		['person: blond hair'],
		['man'],
		['man: blond hair'],
//		['man: red hair'],
//		['man: curly hair'],
//		['man: white hair'],
//		['man: bald'],
		['man: beard'],
		['woman'],
		['woman: blond hair'],
//		['woman: red hair'],
//		['woman: curly hair'],
//		['woman: white hair'],
//		['woman: bald'],
		['older person'],
		['old man'],
		['old woman'],
		['person frowning'],
		['man frowning'],
		['woman frowning'],
		['person pouting'],
		['man pouting'],
		['woman pouting'],
		['person gesturing NO'],
		['man gesturing NO'],
		['woman gesturing NO'],
		['person gesturing OK'],
		['man gesturing OK'],
		['woman gesturing OK'],
		['person tipping hand'],
		['man tipping hand'],
		['woman tipping hand'],
		['person raising hand'],
		['man raising hand'],
		['woman raising hand'],
		['person bowing'],
		['man bowing'],
		['woman bowing'],
		['person facepalming'],
		['man facepalming'],
		['woman facepalming'],
		['person shrugging'],
		['man shrugging'],
		['woman shrugging'],
		['man health worker'],
		['woman health worker'],
		['man student'],
		['woman student'],
		['man teacher'],
		['woman teacher'],
		['man judge'],
		['woman judge'],
		['man farmer'],
		['woman farmer'],
		['man cook'],
		['woman cook'],
		['man mechanic'],
		['woman mechanic'],
		['man factory worker'],
		['woman factory worker'],
		['man office worker'],
		['woman office worker'],
		['man scientist'],
		['woman scientist'],
		['man technologist'],
		['woman technologist'],
		['man singer'],
		['woman singer'],
		['man artist'],
		['woman artist'],
		['man pilot'],
		['woman pilot'],
		['man astronaut'],
		['woman astronaut'],
		['man firefighter'],
		['woman firefighter'],
		['police officer'],
		['man police officer'],
		['woman police officer'],
		['detective'],
		['man detective'],
		['woman detective'],
		['guard'],
		['man guard'],
		['woman guard'],
		['construction worker'],
		['man construction worker'],
		['woman construction worker'],
		['prince'],
		['princess'],
		['person wearing turban'],
		['man wearing turban'],
		['woman wearing turban'],
		['man with Chinese cap'],
		['woman with headscarf'],
		['man in tuxedo'],
		['bride with veil'],
		['pregnant woman'],
		['breast-feeding'],
		['baby angel'],
		['Santa Claus'],
		['Mrs. Claus'],
		['superhero'],
//		['man superhero'],
//		['woman superhero'],
		['supervillain'],
//		['man supervillain'],
//		['woman supervillain'],
		['mage'],
		['man mage'],
		['woman mage'],
		['fairy'],
		['man fairy'],
		['woman fairy'],
		['vampire'],
		['man vampire'],
		['woman vampire'],
		['merperson'],
		['merman'],
		['mermaid'],
		['elf'],
		['man elf'],
		['woman elf'],
		['genie'],
		['man genie'],
		['woman genie'],
		['zombie'],
		['man zombie'],
		['woman zombie'],
		['person getting massage'],
		['man getting massage'],
		['woman getting massage'],
		['person getting haircut'],
		['man getting haircut'],
		['woman getting haircut'],
		['person walking'],
		['man walking'],
		['woman walking'],
		['person running'],
		['man running'],
		['woman running'],
		['woman dancing'],
		['man dancing'],
		['man in suit levitating'],
		['people with bunny ears'],
		['men with bunny ears'],
		['women with bunny ears'],
		['person in steamy room'],
		['man in steamy room'],
		['woman in steamy room'],
		['person climbing'],
		['man climbing'],
		['woman climbing'],
		['women holding hands'],
		['woman and man holding hands'],
		['men holding hands'],
		['kiss'],
		['kiss: woman, man'],
		['kiss: man, man'],
		['kiss: woman, woman'],
		['couple with heart'],
		['couple with heart: woman, man'],
		['couple with heart: man, man'],
		['couple with heart: woman, woman'],
		['family'],
		['family: man, woman, boy'],
		['family: man, woman, girl'],
		['family: man, woman, girl, boy'],
		['family: man, woman, boy, boy'],
		['family: man, woman, girl, girl'],
		['family: man, man, boy'],
		['family: man, man, girl'],
		['family: man, man, girl, boy'],
		['family: man, man, boy, boy'],
		['family: man, man, girl, girl'],
		['family: woman, woman, boy'],
		['family: woman, woman, girl'],
		['family: woman, woman, girl, boy'],
		['family: woman, woman, boy, boy'],
		['family: woman, woman, girl, girl'],
		['family: man, boy'],
		['family: man, boy, boy'],
		['family: man, girl'],
		['family: man, girl, boy'],
		['family: man, girl, girl'],
		['family: woman, boy'],
		['family: woman, boy, boy'],
		['family: woman, girl'],
		['family: woman, girl, boy'],
		['family: woman, girl, girl']
	], [	// --- animals
		['monkey face'],
		['monkey'],
		['gorilla'],
		['dog face'],
		['dog'],
		['poodle'],
		['wolf face'],
		['fox face'],
		['raccoon'],
		['cat face'],
		['cat'],
		['lion face'],
		['tiger face'],
		['tiger'],
		['leopard'],
		['horse face'],
		['horse'],
		['unicorn face'],
		['zebra'],
		['deer'],
		['cow face'],
		['ox'],
		['water buffalo'],
		['cow'],
		['pig face'],
		['pig'],
		['boar'],
		['pig nose'],
		['ram'],
		['ewe'],
		['goat'],
		['camel'],
		['two-hump camel'],
		['llama'],
		['giraffe'],
		['elephant'],
		['rhinoceros'],
		['hippopotamus'],
		['mouse face'],
		['mouse'],
		['rat'],
		['hamster face'],
		['rabbit face'],
		['rabbit'],
		['chipmunk'],
		['hedgehog'],
		['bat'],
		['bear face'],
		['koala'],
		['panda face'],
		['kangaroo'],
		['badger'],
		['turkey'],
		['chicken'],
		['rooster'],
		['hatching chick'],
		['baby chick'],
		['front-facing baby chick'],
		['bird'],
		['penguin'],
		['dove'],
		['eagle'],
		['duck'],
		['swan'],
		['owl'],
		['peacock'],
		['parrot'],
		['frog face'],
		['crocodile'],
		['turtle'],
		['lizard'],
		['snake'],
		['dragon face'],
		['dragon'],
		['sauropod'],
		['T-Rex'],
		['spouting whale'],
		['whale'],
		['dolphin'],
		['fish'],
		['tropical fish'],
		['blowfish'],
		['shark'],
		['octopus'],
		['spiral shell'],
		['snail'],
		['butterfly'],
		['bug'],
		['ant'],
		['honeybee'],
		['lady beetle'],
		['cricket'],
		['spider'],
		['spider web'],
		['scorpion'],
		['mosquito'],
		['microbe'],
		['paw prints']
	], [	// --- nature
		['bouquet'],
		['cherry blossom'],
		['white flower'],
		['rosette'],
		['rose'],
		['wilted flower'],
		['hibiscus'],
		['sunflower'],
		['blossom'],
		['tulip'],
		['seedling'],
		['evergreen tree'],
		['deciduous tree'],
		['palm tree'],
		['cactus'],
		['sheaf of rice'],
		['herb'],
		['shamrock'],
		['four leaf clover'],
		['maple leaf'],
		['fallen leaf'],
		['leaf fluttering in wind'],
		['new moon'],
		['waxing crescent moon'],
		['first quarter moon'],
		['waxing gibbous moon'],
		['full moon'],
		['waning gibbous moon'],
		['last quarter moon'],
		['waning crescent moon'],
		['crescent moon'],
		['new moon face'],
		['first quarter moon face'],
		['last quarter moon face'],
		['thermometer'],
		['sun'],
		['full moon face'],
		['sun with face'],
		['star'],
		['glowing star'],
		['shooting star'],
		['cloud'],
		['sun behind cloud'],
		['cloud with lightning and rain'],
		['sun behind small cloud'],
		['sun behind large cloud'],
		['sun behind rain cloud'],
		['cloud with rain'],
		['cloud with snow'],
		['cloud with lightning'],
		['tornado'],
		['fog'],
		['wind face'],
		['cyclone'],
		['rainbow'],
		['closed umbrella'],
		['umbrella'],
		['umbrella with rain drops'],
		['umbrella on ground'],
		['high voltage'],
		['snowflake'],
		['snowman'],
		['snowman without snow'],
		['comet'],
		['fire'],
		['droplet'],
		['water wave']
	], [	// --- food & drink
		['grapes'],
		['melon'],
		['watermelon'],
		['tangerine'],
		['lemon'],
		['banana'],
		['pineapple'],
		['mango'],
		['red apple'],
		['green apple'],
		['pear'],
		['peach'],
		['cherries'],
		['strawberry'],
		['kiwi fruit'],
		['tomato'],
		['coconut'],
		['avocado'],
		['eggplant'],
		['potato'],
		['carrot'],
		['ear of corn'],
		['hot pepper'],
		['cucumber'],
		['leafy green'],
		['broccoli'],
		['mushroom'],
		['peanuts'],
		['chestnut'],
		['bread'],
		['croissant'],
		['baguette bread'],
		['pretzel'],
		['bagel'],
		['pancakes'],
		['cheese wedge'],
		['meat on bone'],
		['poultry leg'],
		['cut of meat'],
		['bacon'],
		['hamburger'],
		['french fries'],
		['pizza'],
		['hot dog'],
		['sandwich'],
		['taco'],
		['burrito'],
		['stuffed flatbread'],
		['egg'],
		['cooking'],
		['shallow pan of food'],
		['pot of food'],
		['bowl with spoon'],
		['green salad'],
		['popcorn'],
		['salt'],
		['canned food'],
		['bento box'],
		['rice cracker'],
		['rice ball'],
		['cooked rice'],
		['curry rice'],
		['steaming bowl'],
		['spaghetti'],
		['roasted sweet potato'],
		['oden'],
		['sushi'],
		['fried shrimp'],
		['fish cake with swirl'],
		['moon cake'],
		['dango'],
		['dumpling'],
		['fortune cookie'],
		['takeout box'],
		['crab'],
		['lobster'],
		['shrimp'],
		['squid'],
		['soft ice cream'],
		['shaved ice'],
		['ice cream'],
		['doughnut'],
		['cookie'],
		['birthday cake'],
		['shortcake'],
		['cupcake'],
		['pie'],
		['chocolate bar'],
		['candy'],
		['lollipop'],
		['custard'],
		['honey pot'],
		['baby bottle'],
		['glass of milk'],
		['hot beverage'],
		['teacup without handle'],
		['sake'],
		['bottle with popping cork'],
		['wine glass'],
		['cocktail glass'],
		['tropical drink'],
		['beer mug'],
		['clinking beer mugs'],
		['clinking glasses'],
		['tumbler glass'],
		['cup with straw'],
		['chopsticks'],
		['fork and knife with plate'],
		['fork and knife'],
		['spoon'],
		['kitchen knife'],
		['amphora']
	], [	// --- travels & places
		['globe showing Europe-Africa'],
		['globe showing Americas'],
		['globe showing Asia-Australia'],
		['globe with meridians'],
		['world map'],
		['map of Japan'],
		['compass'],
		['snow-capped mountain'],
		['mountain'],
		['volcano'],
		['mount fuji'],
		['camping'],
		['beach with umbrella'],
		['desert'],
		['desert island'],
		['national park'],
		['stadium'],
		['classical building'],
		['building construction'],
		['brick'],
		['houses'],
		['derelict house'],
		['house'],
		['house with garden'],
		['office building'],
		['Japanese post office'],
		['post office'],
		['hospital'],
		['bank'],
		['hotel'],
		['love hotel'],
		['convenience store'],
		['school'],
		['department store'],
		['factory'],
		['Japanese castle'],
		['castle'],
		['wedding'],
		['Tokyo tower'],
		['Statue of Liberty'],
		['church'],
		['mosque'],
		['synagogue'],
		['shinto shrine'],
		['kaaba'],
		['fountain'],
		['tent'],
		['foggy'],
		['night with stars'],
		['cityscape'],
		['sunrise over mountains'],
		['sunrise'],
		['cityscape at dusk'],
		['sunset'],
		['bridge at night'],
		['♨ ♨ ♨ ♨ hot springs'],
		['milky way'],
		['carousel horse'],
		['ferris wheel'],
		['roller coaster'],
		['barber pole'],
		['circus tent'],
		['locomotive'],
		['railway car'],
		['high-speed train'],
		['bullet train'],
		['train'],
		['metro'],
		['light rail'],
		['station'],
		['tram'],
		['monorail'],
		['mountain railway'],
		['tram car'],
		['bus'],
		['oncoming bus'],
		['trolleybus'],
		['minibus'],
		['ambulance'],
		['fire engine'],
		['police car'],
		['oncoming police car'],
		['taxi'],
		['oncoming taxi'],
		['automobile'],
		['oncoming automobile'],
		['sport utility vehicle'],
		['delivery truck'],
		['articulated lorry'],
		['tractor'],
		['racing car'],
		['motorcycle'],
		['motor scooter'],
		['bicycle'],
		['kick scooter'],
		['skateboard'],
		['bus stop'],
		['motorway'],
		['railway track'],
		['oil drum'],
		['fuel pump'],
		['police car light'],
		['horizontal traffic light'],
		['vertical traffic light'],
		['stop sign'],
		['construction'],
		['anchor'],
		['sailboat'],
		['canoe'],
		['speedboat'],
		['passenger ship'],
		['ferry'],
		['motor boat'],
		['ship'],
		['airplane'],
		['small airplane'],
		['airplane departure'],
		['airplane arrival'],
		['seat'],
		['helicopter'],
		['suspension railway'],
		['mountain cableway'],
		['aerial tramway'],
		['satellite'],
		['rocket'],
		['flying saucer'],
		['bellhop bell'],
		['luggage']
	], [	// --- activities & sport
		['person fencing'],
		['horse racing'],
		['skier'],
		['snowboarder'],
		['person golfing'],
		['man golfing'],
		['woman golfing'],
		['person surfing'],
		['man surfing'],
		['woman surfing'],
		['person rowing boat'],
		['man rowing boat'],
		['woman rowing boat'],
		['person swimming'],
		['man swimming'],
		['woman swimming'],
		['person bouncing ball'],
		['man bouncing ball'],
		['woman bouncing ball'],
		['person lifting weights'],
		['man lifting weights'],
		['woman lifting weights'],
		['person biking'],
		['man biking'],
		['woman biking'],
		['person mountain biking'],
		['man mountain biking'],
		['woman mountain biking'],
		['person cartwheeling'],
		['man cartwheeling'],
		['woman cartwheeling'],
		['people wrestling'],
		['men wrestling'],
		['women wrestling'],
		['person playing water polo'],
		['man playing water polo'],
		['woman playing water polo'],
		['person playing handball'],
		['man playing handball'],
		['woman playing handball'],
		['person juggling'],
		['man juggling'],
		['woman juggling'],
		['person in lotus position'],
		['man in lotus position'],
		['woman in lotus position'],
		['person taking bath'],
		['person in bed'],
		['soccer ball'],
		['baseball'],
		['softball'],
		['basketball'],
		['volleyball'],
		['american football'],
		['rugby football'],
		['tennis'],
		['flying disc'],
		['bowling'],
		['cricket game'],
		['field hockey'],
		['ice hockey'],
		['lacrosse'],
		['ping pong'],
		['badminton'],
		['boxing glove'],
		['martial arts uniform'],
		['goal net'],
		['flag in hole'],
		['ice skate'],
		['fishing pole'],
		['running shirt'],
		['skis'],
		['sled'],
		['curling stone'],
		['military medal'],
		['trophy'],
		['sports medal'],
		['direct hit'],
		['crystal ball'],
		['nazar amulet'],
		['video game'],
		['joystick'],
		['slot machine'],
		['game die'],
		['jigsaw'],
		['teddy bear'],
		['mahjong red dragon'],
		['flower playing cards'],
		['performing arts'],
		['framed picture'],
		['artist palette'],
		['thread'],
		['yarn']
	], [	// --- objects
		['bomb'],
		['speech balloon'],
		['eye in speech bubble'],
		['left speech bubble'],
		['right anger bubble'],
		['thought balloon'],
		['zzz'],
		['hourglass done'],
		['hourglass not done'],
		['watch'],
		['alarm clock'],
		['stopwatch'],
		['timer clock'],
		['mantelpiece clock'],
		['twelve o’clock'],
		['twelve-thirty'],
		['one o’clock'],
		['one-thirty'],
		['two o’clock'],
		['two-thirty'],
		['three o’clock'],
		['three-thirty'],
		['four o’clock'],
		['four-thirty'],
		['five o’clock'],
		['five-thirty'],
		['six o’clock'],
		['six-thirty'],
		['seven o’clock'],
		['seven-thirty'],
		['eight o’clock'],
		['eight-thirty'],
		['nine o’clock'],
		['nine-thirty'],
		['ten o’clock'],
		['ten-thirty'],
		['eleven o’clock'],
		['eleven-thirty'],
		['jack-o-lantern'],
		['Christmas tree'],
		['fireworks'],
		['sparkler'],
		['firecracker'],
		['sparkles'],
		['balloon'],
		['party popper'],
		['confetti ball'],
		['tanabata tree'],
		['pine decoration'],
		['Japanese dolls'],
		['carp streamer'],
		['wind chime'],
		['moon viewing ceremony'],
		['red envelope'],
		['ribbon'],
		['wrapped gift'],
		['reminder ribbon'],
		['admission tickets'],
		['ticket'],
		['glasses'],
		['sunglasses'],
		['goggles'],
		['lab coat'],
		['necktie'],
		['t-shirt'],
		['jeans'],
		['scarf'],
		['gloves'],
		['coat'],
		['socks'],
		['dress'],
		['kimono'],
		['bikini'],
		['woman’s clothes'],
		['purse'],
		['handbag'],
		['clutch bag'],
		['shopping bags'],
		['backpack'],
		['man’s shoe'],
		['running shoe'],
		['hiking boot'],
		['flat shoe'],
		['high-heeled shoe'],
		['woman’s sandal'],
		['woman’s boot'],
		['crown'],
		['woman’s hat'],
		['top hat'],
		['graduation cap'],
		['billed cap'],
		['rescue worker’s helmet'],
		['prayer beads'],
		['lipstick'],
		['ring'],
		['gem stone'],
		['loudspeaker'],
		['megaphone'],
		['postal horn'],
		['bell'],
		['studio microphone'],
		['level slider'],
		['control knobs'],
		['microphone'],
		['headphone'],
		['radio'],
		['saxophone'],
		['guitar'],
		['musical keyboard'],
		['trumpet'],
		['violin'],
		['drum'],
		['mobile phone'],
		['mobile phone with arrow'],
		['telephone'],
		['telephone receiver'],
		['pager'],
		['fax machine'],
		['battery'],
		['electric plug'],
		['laptop computer'],
		['desktop computer'],
		['printer'],
		['keyboard'],
		['computer mouse'],
		['trackball'],
		['computer disk'],
		['floppy disk'],
		['optical disk'],
		['dvd'],
		['abacus'],
		['movie camera'],
		['film frames'],
		['film projector'],
		['clapper board'],
		['television'],
		['camera'],
		['camera with flash'],
		['video camera'],
		['videocassette'],
		['magnifying glass tilted left'],
		['magnifying glass tilted right'],
		['candle'],
		['light bulb'],
		['flashlight'],
		['red paper lantern'],
		['notebook with decorative cover'],
		['closed book'],
		['open book'],
		['green book'],
		['blue book'],
		['orange book'],
		['books'],
		['notebook'],
		['ledger'],
		['page with curl'],
		['scroll'],
		['page facing up'],
		['newspaper'],
		['rolled-up newspaper'],
		['bookmark tabs'],
		['bookmark'],
		['label'],
		['money bag'],
		['yen banknote'],
		['dollar banknote'],
		['euro banknote'],
		['pound banknote'],
		['money with wings'],
		['credit card'],
		['receipt'],
		['chart increasing with yen'],
		['currency exchange'],
		['heavy dollar sign'],
		['envelope'],
		['e-mail'],
		['incoming envelope'],
		['envelope with arrow'],
		['outbox tray'],
		['inbox tray'],
		['package'],
		['closed mailbox with raised flag'],
		['closed mailbox with lowered flag'],
		['open mailbox with raised flag'],
		['open mailbox with lowered flag'],
		['postbox'],
		['ballot box with ballot'],
		['pencil'],
		['black nib'],
		['fountain pen'],
		['pen'],
		['paintbrush'],
		['crayon'],
		['memo'],
		['briefcase'],
		['file folder'],
		['open file folder'],
		['card index dividers'],
		['calendar'],
		['tear-off calendar'],
		['spiral notepad'],
		['spiral calendar'],
		['card index'],
		['chart increasing'],
		['chart decreasing'],
		['bar chart'],
		['clipboard'],
		['pushpin'],
		['round pushpin'],
		['paperclip'],
		['linked paperclips'],
		['straight ruler'],
		['triangular ruler'],
		['scissors'],
		['card file box'],
		['file cabinet'],
		['wastebasket'],
		['locked'],
		['unlocked'],
		['locked with pen'],
		['locked with key'],
		['key'],
		['old key'],
		['hammer'],
		['pick'],
		['hammer and pick'],
		['hammer and wrench'],
		['dagger'],
		['crossed swords'],
		['pistol'],
		['bow and arrow'],
		['shield'],
		['wrench'],
		['nut and bolt'],
		['gear'],
		['clamp'],
		['balance scale'],
		['link'],
		['chains'],
		['toolbox'],
		['magnet'],
		['alembic'],
		['test tube'],
		['petri dish'],
		['dna'],
		['microscope'],
		['telescope'],
		['satellite antenna'],
		['syringe'],
		['pill'],
		['door'],
		['bed'],
		['couch and lamp'],
		['toilet'],
		['shower'],
		['bathtub'],
		['lotion bottle'],
		['safety pin'],
		['broom'],
		['basket'],
		['roll of paper'],
		['soap'],
		['sponge'],
		['fire extinguisher'],
		['shopping cart'],
		['cigarette'],
		['coffin'],
		['funeral urn'],
		['moai']
	], [	// symbols
		['kiss mark'],
		['love letter'],
		['heart with arrow'],
		['heart with ribbon'],
		['sparkling heart'],
		['growing heart'],
		['beating heart'],
		['revolving hearts'],
		['two hearts'],
		['heart decoration'],
		['heavy heart exclamation'],
		['broken heart'],
		['red heart'],
		['orange heart'],
		['yellow heart'],
		['green heart'],
		['blue heart'],
		['purple heart'],
		['black heart'],
		['hundred points'],
		['anger symbol'],
		['collision'],
		['dizzy'],
		['sweat droplets'],
		['dashing away'],
		['hole'],
		['muted speaker'],
		['speaker low volume'],
		['speaker medium volume'],
		['speaker high volume'],
		['bell with slash'],
		['musical score'],
		['musical note'],
		['musical notes'],
		['spade suit'],
		['heart suit'],
		['diamond suit'],
		['club suit'],
		['chess pawn'],
		['joker'],
		['ATM sign'],
		['litter in bin sign'],
		['potable water'],
		['wheelchair symbol'],
		['men’s room'],
		['women’s room'],
		['restroom'],
		['baby symbol'],
		['water closet'],
		['passport control'],
		['customs'],
		['baggage claim'],
		['left luggage'],
		['warning'],
		['children crossing'],
		['no entry'],
		['prohibited'],
		['no bicycles'],
		['no smoking'],
		['no littering'],
		['non-potable water'],
		['no pedestrians'],
		['no mobile phones'],
		['no one under eighteen'],
		['radioactive'],
		['biohazard'],
		['up arrow'],
		['up-right arrow'],
		['right arrow'],
		['down-right arrow'],
		['down arrow'],
		['down-left arrow'],
		['left arrow'],
		['up-left arrow'],
		['up-down arrow'],
		['left-right arrow'],
		['right arrow curving left'],
		['left arrow curving right'],
		['right arrow curving up'],
		['right arrow curving down'],
		['clockwise vertical arrows'],
		['counterclockwise arrows button'],
		['BACK arrow'],
		['END arrow'],
		['ON! arrow'],
		['SOON arrow'],
		['TOP arrow'],
		['place of worship'],
		['atom symbol'],
		['om'],
		['star of David'],
		['wheel of dharma'],
		['yin yang'],
		['latin cross'],
		['orthodox cross'],
		['star and crescent'],
		['peace symbol'],
		['menorah'],
		['dotted six-pointed star'],
		['Aries'],
		['Taurus'],
		['Gemini'],
		['Cancer'],
		['Leo'],
		['Virgo'],
		['Libra'],
		['Scorpio'],
		['Sagittarius'],
		['Capricorn'],
		['Aquarius'],
		['Pisces'],
		['Ophiuchus'],
		['shuffle tracks button'],
		['repeat button'],
		['repeat single button'],
		['play button'],
		['fast-forward button'],
		['next track button'],
		['play or pause button'],
		['reverse button'],
		['fast reverse button'],
		['last track button'],
		['upwards button'],
		['fast up button'],
		['downwards button'],
		['fast down button'],
		['pause button'],
		['stop button'],
		['record button'],
		['eject button'],
		['cinema'],
		['dim button'],
		['bright button'],
		['antenna bars'],
		['vibration mode'],
		['mobile phone off'],
		['female sign'],
		['male sign'],
		['medical symbol'],
		['infinity'],
		['recycling symbol'],
		['fleur-de-lis'],
		['trident emblem'],
		['name badge'],
		['Japanese symbol for beginner'],
		['heavy large circle'],
		['white heavy check mark'],
		['ballot box with check'],
		['heavy check mark'],
		['heavy multiplication x'],
		['cross mark'],
		['cross mark button'],
		['heavy plus sign'],
		['heavy minus sign'],
		['heavy division sign'],
		['curly loop'],
		['double curly loop'],
		['parternation mark'],
		['eight-spoked asterisk'],
		['eight-pointed star'],
		['sparkle'],
		['double exclamation mark'],
		['exclamation question mark'],
		['question mark'],
		['white question mark'],
		['white exclamation mark'],
		['exclamation mark'],
		['wavy dash'],
		['copyright'],
		['registered'],
		['trade mark'],
		['keycap #'],
		['keycap *'],
		['keycap 0'],
		['keycap 1'],
		['keycap 2'],
		['keycap 3'],
		['keycap 4'],
		['keycap 5'],
		['keycap 6'],
		['keycap 7'],
		['keycap 8'],
		['keycap 9'],
		['input latin uppercase'],
		['input latin lowercase'],
		['input numbers'],
		['input symbols'],
		['input latin letters'],
		['button (blood type)'],
		['AB button (blood type)'],
		['button (blood type)'],
		['CL button'],
		['COOL button'],
		['FREE button'],
		['information'],
		['ID button'],
		['circled M'],
		['NEW button'],
		['NG button'],
		['button (blood type)'],
		['OK button'],
		['button'],
		['SOS button'],
		['UP! button'],
		['VS button'],
		['Japanese “here” button'],
		['Japanese “service charge” button'],
		['Japanese “monthly amount” button'],
		['Japanese “not free of charge” button'],
		['Japanese “reserved” button'],
		['Japanese “bargain” button'],
		['Japanese “discount” button'],
		['Japanese “free of charge” button'],
		['Japanese “prohibited” button'],
		['Japanese “acceptable” button'],
		['Japanese “application” button'],
		['Japanese “passing grade” button'],
		['Japanese “vacancy” button'],
		['Japanese “congratulations” button'],
		['Japanese “secret” button'],
		['Japanese “open for business” button'],
		['Japanese “no vacancy” button'],
		['red circle'],
		['blue circle'],
		['white circle'],
		['black circle'],
		['white large square'],
		['black large square'],
		['black medium square'],
		['white medium square'],
		['white medium-small square'],
		['black medium-small square'],
		['white small square'],
		['black small square'],
		['large orange diamond'],
		['large blue diamond'],
		['small orange diamond'],
		['small blue diamond'],
		['red triangle pointed up'],
		['red triangle pointed down'],
		['diamond with dot'],
		['radio button'],
		['black square button'],
		['white square button']
	], [	// --- flags
		['chequered flag'],
		['triangular flag'],
		['crossed flags'],
		['black flag'],
		['white flag'],
		['rainbow flag'],
		['pirate flag'],
		['Afghanistan'],
		['Åland Islands'],
		['Albania'],
		['Algeria'],
		['American Samoa'],
		['Andorra'],
		['Angola'],
		['Anguilla'],
		['Antarctica'],
		['Antigua & Barbuda'],
		['Argentina'],
		['Armenia'],
		['Aruba'],
		['Ascension Island'],
		['Australia'],
		['Austria'],
		['Azerbaijan'],
		['Bahamas'],
		['Bahrain'],
		['Bangladesh'],
		['Barbados'],
		['Belarus'],
		['Belgium'],
		['Belize'],
		['Benin'],
		['Bermuda'],
		['Bhutan'],
		['Bolivia'],
		['Bosnia & Herzegovina'],
		['Botswana'],
		['Bouvet Island'],
		['Brazil'],
		['British Indian Ocean Territory'],
		['British Virgin Islands'],
		['Brunei'],
		['Bulgaria'],
		['Burkina Faso'],
		['Burundi'],
		['Cambodia'],
		['Cameroon'],
		['Canada'],
		['Canary Islands'],
		['Cape Verde'],
		['Caribbean Netherlands'],
		['Cayman Islands'],
		['Central African Republic'],
		['Ceuta & Melilla'],
		['Chad'],
		['Chile'],
		['China'],
		['Christmas Island'],
		['Clipperton Island'],
		['Cocos (Keeling) Islands'],
		['Colombia'],
		['Comoros'],
		['Congo - Kinshasa'],
		['Congo - Brazzaville'],
		['Cook Islands'],
		['Costa Rica'],
		['Côte d’Ivoire'],
		['Croatia'],
		['Cuba'],
		['Curaçao'],
		['Cyprus'],
		['Czechia'],
		['Denmark'],
		['Diego Garcia'],
		['Djibouti'],
		['Dominica'],
		['Dominican Republic'],
		['Ecuador'],
		['Egypt'],
		['El Salvador'],
//		['England'],
		['Equatorial Guinea'],
		['Eritrea'],
		['Estonia'],
		['Ethiopia'],
		['European Union'],
		['Falkland Islands'],
		['Faroe Islands'],
		['Fiji'],
		['Finland'],
		['France'],
		['French Guiana'],
		['French Polynesia'],
		['French Southern Territories'],
		['Gabon'],
		['Gambia'],
		['Georgia'],
		['Germany'],
		['Ghana'],
		['Gibraltar'],
		['Greece'],
		['Greenland'],
		['Grenada'],
		['Guadeloupe'],
		['Guam'],
		['Guatemala'],
		['Guernsey'],
		['Guinea'],
		['Guinea-Bissau'],
		['Guyana'],
		['Haiti'],
		['Heard & McDonald Islands'],
		['Honduras'],
		['Hong Kong SAR China'],
		['Hungary'],
		['Iceland'],
		['India'],
		['Indonesia'],
		['Iran'],
		['Iraq'],
		['Ireland'],
		['Isle of Man'],
		['Israel'],
		['Italy'],
		['Jamaica'],
		['Japan'],
		['Jersey'],
		['Jordan'],
		['Kazakhstan'],
		['Kenya'],
		['Kiribati'],
		['Kosovo'],
		['Kuwait'],
		['Kyrgyzstan'],
		['Laos'],
		['Latvia'],
		['Lebanon'],
		['Lesotho'],
		['Liberia'],
		['Libya'],
		['Liechtenstein'],
		['Lithuania'],
		['Luxembourg'],
		['Macau SAR China'],
		['Macedonia'],
		['Madagascar'],
		['Malawi'],
		['Malaysia'],
		['Maldives'],
		['Mali'],
		['Malta'],
		['Marshall Islands'],
		['Martinique'],
		['Mauritania'],
		['Mauritius'],
		['Mayotte'],
		['Mexico'],
		['Micronesia'],
		['Moldova'],
		['Monaco'],
		['Mongolia'],
		['Montenegro'],
		['Montserrat'],
		['Morocco'],
		['Mozambique'],
		['Myanmar (Burma)'],
		['Namibia'],
		['Nauru'],
		['Nepal'],
		['Netherlands'],
		['New Caledonia'],
		['New Zealand'],
		['Nicaragua'],
		['Niger'],
		['Nigeria'],
		['Niue'],
		['Norfolk Island'],
		['North Korea'],
		['Northern Mariana Islands'],
		['Norway'],
		['Oman'],
		['Pakistan'],
		['Palau'],
		['Palestinian Territories'],
		['Panama'],
		['Papua New Guinea'],
		['Paraguay'],
		['Peru'],
		['Philippines'],
		['Pitcairn Islands'],
		['Poland'],
		['Portugal'],
		['Puerto Rico'],
		['Qatar'],
		['Réunion'],
		['Romania'],
		['Russia'],
		['Rwanda'],
		['Samoa'],
		['San Marino'],
		['São Tomé & Príncipe'],
		['Saudi Arabia'],
//		['Scotland'],
		['Senegal'],
		['Serbia'],
		['Seychelles'],
		['Sierra Leone'],
		['Singapore'],
		['Sint Maarten'],
		['Slovakia'],
		['Slovenia'],
		['Solomon Islands'],
		['Somalia'],
		['South Georgia & South Sandwich Islands'],
		['South Korea'],
		['South Sudan'],
		['South Africa'],
		['Spain'],
		['Sri Lanka'],
		['St. Barthélemy'],
		['St. Kitts & Nevis'],
		['St. Lucia'],
		['St. Martin'],
		['St. Pierre & Miquelon'],
		['St. Helena'],
		['St. Vincent & Grenadines'],
		['Sudan'],
		['Suriname'],
		['Svalbard & Jan Mayen'],
		['Swaziland'],
		['Sweden'],
		['Switzerland'],
		['Syria'],
		['Taiwan'],
		['Tajikistan'],
		['Tanzania'],
		['Thailand'],
		['Timor-Leste'],
		['Togo'],
		['Tokelau'],
		['Tonga'],
		['Trinidad & Tobago'],
		['Tristan da Cunha'],
		['Tunisia'],
		['Turkey'],
		['Turkmenistan'],
		['Turks & Caicos Islands'],
		['Tuvalu'],
		['U.S. Outlying Islands'],
		['U.S. Virgin Islands'],
		['Uganda'],
		['Ukraine'],
		['United Arab Emirates'],
		['United Kingdom'],
		['United Nations'],
		['United States'],
		['Uruguay'],
		['Uzbekistan'],
		['Vanuatu'],
		['Vatican City'],
		['Venezuela'],
		['Vietnam'],
//		['Wales'],
		['Wallis & Futuna'],
		['Western Sahara'],
		['Yemen'],
		['Zambia'],
		['Zimbabwe']
	]
];
